serge-rgb/milton

- src/milton.h
"buffer" is a reserved keyword in glsl 430 or ARB_buffer_storage, so not technically in 330, but oh well.
> Fix shader compile on AMD hardware

- src/platform_mac.cc
- src/platform_mac_gui.mm
- tundra.lua
I went ahead and implemented this, just tested by putting each function in milton_main.
Added separate file instead of renaming existing file because when an Objective-C file imports SDL it imports Carbon’s legacy Rect struct which conflicts with Milton’s Rect.
> Implement macOS dialogs

- src/gui.cc
When the canvas is unsaved, selecting the "New Canvas" dialog in the menu, choosing either option can sometimes crash the program, specifically on https://github.com/serge-rgb/milton/blob/04354239d31f479ed245de7e7a3bd1570e26a80b/src/gui.cc#L424
This happens because `milton_reset_canvas_and_set_default` calls `arena_bootstrap` on `milton_state->canvas`, but due to the nature of the arena system this may actually change the pointer of `canvas`.
In `milton_imgui_tick` there is a local var `canvas` that gets assigned at the beginning of the function. When `milton_state->canvas` changes, the local `canvas` is not updated and will cause a crash because it points to a faulty memory address.
What my patch does is update the `canvas` variable right after the canvas is reset. This fixes the issue.
> Fix a crash

- CMakeLists.txt
- src/common.h
- src/platform_linux.cc
I had some issues building for linux so I fixed them.
The main course is the CMake. It disregards the inlined SDL2 source and finds the precompiled binaries on disk along with X11, XInput, OpenGL and GTK2
The side dish would be the couple of stub's in platform_linux.cpp, the most interesting one being platform_ui_scale for it returns 1.
Now it builds for me. Stylus pressure works too BTW.
> Stubs and CMake improvements for linux

- CMakeLists.txt
- README.md
- src/milton_configuration.h
- src/platform_linux.cc
- src/sdl_milton.cc
* `IS_USING_CMAKE` will be defined if compiling with CMake.
* If `IS_USING_CMAKE` is not set, we set`MILTON_DEBUG=1`
* New command line goodies:
* `-DTRY_GL2=1` will define `CMAKE_TRY_GL2` which sets `USE_GL_3_2=0`
* `-DTRY_GL2=3` will define `CMAKE_TRY_GL3` which sets `USE_GL_3_2=1`
* Build types that do something. `-DCMAKE_BUILD_TYPE=Release` compiles with `-O3`optimization. `-DCMAKE_BUILD_TYPE=Debug` sets `MILTON_DEBUG=1` and compiles with `-g`
I don't have access to a windows machine so I can't confirm if the CMake changes will work on windows.
* Fixed a possible overflow in linux `platform_fname_at_config`. `strncat` was being called with the max character paramater being the size of the target buffer and not the remaining space in it. We now count how many characters the final …
> CMake switches for OpenGL2/3, Release and Debug. Fixed a possible overflow in linux platform_fname_at_config

- CMakeLists.txt
CMake complains about trailing spaces in the link targets on Ubuntu.
This fixes it by removing any trailing/leading whitespaces by using string(STRIP a b)
> Fixed CMake warning on Ubuntu 16.04

- src/platform_linux.cc
- src/platform_unix.h
In aab239225a1145e0be48f71b95daf0584c2f36d0 you removed fopen_unix but only changed platorm_mac. This just does the same change in platform_linux.
> fix linux platform_fopen

- src/milton.cc
Fixes compilation on Linux which errors due to the potential buffer overflow.
> Removed the potential for an overflow in Layer.name

- CMakeLists.txt
- README.md
- build-lin.sh
Introduced a build-lin.sh bash script that does the following:
1. Builds cmake and installs its static libraries and linux-specific headers
into the third_party/SDL2-2.0.3/build/linux64/{lib,include} directories.
2. Build Milton, linking with the SDL libs that were created in step 1.
Prior to this commit, cmake would try to use the system-installed SDL2, which
has a couple of annoyances:
1. It's not uncommon for a system not to have SDL2, so the user has to install it.
It might be a different version than the one that Milton was written to work with,
potentially causing difficult-to-track-down bugs.
2. There was not a FindSDL2.cmake module packaged along with Milton, which could mean
an irritating process of trying to get cmake to find where the SDL2 libraries and
headers live on a …
> Refined the linux build process a bit.

- build-lin.sh
- src/localization.cc
Fixing these two issues allows me to compile Milton on 64-bit Void Linux.
> Fix Void Linux compilation

- src/gui.cc
I've implemented double click layer renaming. Several things that aren't great:
- you can cancel/confirm the name change by either clicking on a different layer or by pressing Enter. What I think it needs is ability to cancel/confirm by clicking LMB anywhere.
- two static variables have been added. Not necessarily a good idea. Is there a better place to store the state?
It's not ready for merging but just wanted to suggest it and get your take on it @serge-rgb .
> Change layer renaming to double clicking

- src/gui.cc
- src/localization.cc
- src/localization.h
- src/persist.h
- src/platform.h
- src/sdl_milton.cc
First let me say what a nice tool you created here! I like to have my monitor rotated 90° and then put my tool windows up top. That is why I created issue #137. I did not want to have to move the windows again every day :-)
Your code base is pretty nice to work with, I have some changes coming up soon but I wanted to start small with this one. I used 4 spaces instead of tabs and made sure to follow your general coding style (snake_case, spaces in the if braces, etc.) so I hope you can merge this without much hassle. If you have anything else that you would like me to fix first, please let me know :-)
> Fix #137: Remember GUI settings

- src/milton.cc
While holding shift and dragging the mouse left/right to change the
brush size, the size previoulsy was able to become negative/very large.
This change clamps it to 1..300, just like the GUI slider.
> Fix #136 clamp brush size to 1..300

- src/gui.cc
- src/milton.cc
- src/persist.cc
- src/platform_linux.cc
- src/platform_unix.cc
- src/renderer.cc
To have a consistent code base, all tabs are now converted to 4 spaces.
> Format tabs as spaces

- src/bindings.cc
- src/platform.h
- src/platform_linux.cc
- src/platform_windows.cc
I am re-creating this pull request on its own branch. Github was kind enough to pretend that I had created a new fork when really it was the old one. This means I accidentally put two PRs in the same repo's master branch... thanks Github! Anyway, here is the original PR text:
When creating a new canvas the old progress might be lost. The user is
queried with a dialog to save their progress. A new option "cancel" is
now available which lets you continue working on the current canvas
instead of creating a new one.
Also, cancelling the save dialog in case you answer "yes" to saving
your progress will also get you back to the current canvas instead of
creating a new one.
IMPORTANT NOTE: I did not test the Linux version with the GTK dialog. I have no Linux dev environment currently set up so I …
>  Fix #140 add Cancel option to new canvas dialog

- src/bindings.cc
- src/bindings.h
- src/sdl_milton.cc
SDLK_TAB=9 and SDLK_ESCAPE=27 are in the ASCII range so they are not
treated differently in the shortcut handler code anymore. This fixes
using ESC in a shortcut. Currently ESC is not used anywhere, that is
why the bug was not found before.
> Fix #142 allow ESC for keyboard shortcut

- src/sdl_milton.cc
In release mode, the file path buffer `buffer` is getting reused after the scope is closed by other variables causing the `mlt_file_path` to become corrupted.
You can reproduce this by passing the `.mlt` file path on the command line or by double-clicking the file. You will see the file name corrupted in the menu bar at the top and new save files appear in the current directory with random names.
The simplest solution is to just remove the scope.
> Fix: prevent mlt_file_path memory from being deinitialized.

- src/sdl_milton.cc
I noticed after certain events (clicking on the GUI, using keyboard shortcuts) that CPU utilization for Milton is increased from `< 1.0%` to `6-7%`.
I debugged the issue and I found that `platform->force_next_frame` is never set to false anywhere in the code. Once it's set to true it will stay always true.
> Fix: set force_next_frame to false at the end of the frame.

- src/bindings.cc
- src/platform.h
- src/platform_linux.cc
- src/platform_mac.mm
- src/platform_windows.cc
**DESCRIPTION**
Closes #149 
On macOS the file `objc/objc.h` defines macros `YES` and `NO` as part of the Objective-C `BOOL` type definition. Milton also defines its own `YesNoCancelAnswer` enumeration type containing values `YES` and `NO`.
On macOS this causes a conflict where the compiler attempts macro expansion on the definitions of `YesNoCancelAnswer::YES` and `YesNoCancelAnswer::NO`. This leads to compilation failure.
To fix this failure, this change renames the constants of `YesNoCancelAnswer` from `YES` to `YES_`, `NO` to `NO_`, and for consistency from `CANCEL` to `CANCEL_`. All occurrences of the previous constants are replaced.
In addition, this change adds the required function `platform_dialog_yesnocancel` to `src/platform_mac.mm`. This displays a Yes/No/Cancel dialog box on …
> Add Yes/No/Cancel Dialog For MacOS

- src/platform.h
End extern "C" block before including platform_unix.h which includes gtk headers. Otherwise, there are many compilation errors, such as:
/usr/include/c++/11.1.0/type_traits:2895:3: error: template with C linkage
2895 |   template<typename _Fn, typename... _Args>
It may be that these errors were not errors before, rather warnings that were silenced, because the error output also contains:
cc1plus: note: unrecognized command-line option ‘-Wno-extern-c-compat’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-c++11-compat-deprecated-writable-strings’ may have been intended to silence earlier diagnostics
Occurs on manjaro when building the milton-git AUR package:
gcc 11.1.0-1
gcc-libs 11.1.0-1
gtk2 2.24.33-2
milton 1.9.0.r9.c2a9dc3
> Fix compile error re: extern "C" linkage on templates

- src/platform_windows.h
win32_log and win32_log_args were not declared extern "C"
even though they were defined extern "C".
Without the fix, build.bat has the following errors:
```
src\platform_windows.cc(372): error C2732: linkage specification contradicts earlier specification for 'win32_log'
src\platform_windows.cc(371): note: see declaration of 'win32_log'
src\platform_windows.cc(383): error C2732: linkage specification contradicts earlier specification for 'win32_log_args'
src\platform_windows.cc(382): note: see declaration of 'win32_log_args'
```
Apologies, this was introduced by me when fixing Linux builds in #190.
> Fix platform_windows broken since #190 extern "C" fix for platform_unix

- src/easytab.h
- src/platform_mac.mm
- src/platform_unix.h
- src/postproc.f.glsl
- src/sdl_milton.cc
Found via `codespell -q 3 -S ./third_party -L apoints,inout`
> Fix trivial source comment typos

- src/bindings.cc
- src/bindings.h
- src/localization.cc
- src/localization.h
- src/milton.cc
- src/milton.h
I implemented DRAG_ZOOM based on how DRAG_BURSH_SIZE works. 
Click and drag up, down to zoom in and out. 
I noticed someone else had already contributed a PR doing the same in a different way but still, I like the way zooming in and out feels with this PR so maybe you want to take that part as a reference
> Drag based zoom

- src/platform_linux.cc
The dialog was displaying Ok and Cancel instead of Yes, No, Cancel
> fix linux platform_dialog_yesnocancel 
